services:
  pdf_service:
    image: huridocs/pdf-document-layout-analysis:v0.0.24
    container_name: pdf_service
    ports:
      - "5060:5060"
    environment:
      - PYTHONPATH=/app
    command: "./start.sh"

  app:
    build: ./app
    container_name: pdf_app
    depends_on:
      - pdf_service
    ports:
      - "8000:8000"
