version: "3.9"
services:
  pdf_service:
    image: huridocs/pdf-document-layout-analysis:latest
    container_name: pdf_service
    ports:
      - "5060:5060"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]  # se tiver GPU
    command: make start_no_gpu   # troque por `make start` se tiver GPU

  app:
    build: ./app
    container_name: pdf_app
    depends_on:
      - pdf_service
    ports:
      - "8000:8000"
